### ISSUE TITLE
Could I get the test set label to host a Kaggle inclass competition?

### ISSUE THREAD

**Issue by Ritchiegit** [google/youtube-8m#127]
I am a first-year graduate student at SJTU and I am also a teaching assistant. I want to host a kaggle inclass competition with video level feature youtube-8m data for students. But I found that I couldn't have access to the data whose labels students don't know.
Could I get some test set label of Youtube 8m dataset for evaluating the result? I mean there is no need for the labels of all test set, part of them (may be the label of 200MB Video features) is  enough. Or if you have some other suggestions, I would also be very grateful!
Thanks in advance!

**Comment by LeegleechN** [comment]
Hi,

I suggest using part of the validation set. Even a 1/10 sample of the validation set will match the test set results very closely.

**Comment by ramcandrews** [comment]
I agree that they should release the test set after the competition has ended.

It might be fun and educational to have the students all contribute to build a test set.

**Comment by Ritchiegit** [comment]
> Hi,
> 
> I suggest using part of the validation set. Even a 1/10 sample of the validation set will match the test set results very closely.

Hi LeegleechN

Thanks for your prompt reply and suggestions! Maybe I should delabel part of the dataset and randomly sample them. 

Thanks again!

**Comment by Ritchiegit** [comment]
> I agree that they should release the test set after the competition has ended. It might be fun and educational to have the students all contribute to build a test set.

Hi ramcandrews,

Thanks for your suggestion. This sounds very educational and interesting! I am not sure is there need original data and very large and too computing resources to regenerate test set~ I will talk with my professor later.

Thank you~
